### ISSUE TITLE
Build input file cannot be found

### ISSUE THREAD

**Issue by juliuspleunes4** [borarak/GStreamerSwiftUIDemo#1]
Hi! When I compile the code to the simulator, it works perfectly, but when I try to send it to my phone I get the notification:
Build input file cannot be found: '/Users/juliuspleunes/Library/Developer/Xcode/DerivedData/GStreamerSwiftUIDemo-hjdzklcujcliqnbtoohxhxxpzgax/Build/Products/Release-iphoneos/GStreamerSwiftUIDemo.app/GStreamerSwiftUIDemo'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

How do I fix this? ChatGPT and the internet can't seem to give me the right answer :(

**Comment by ghost** [comment]
It caused by excluding the arm64 architecture from the project.
1. Try Go to "Build setting" and search for "Exclude Architectures".
2. remove the "arm64" architecture.
3. build it again.

:-)

**Comment by juliuspleunes4** [comment]
> It caused by excluding the arm64 architecture from the project.
> 
> 1. Try Go to "Build setting" and search for "Exclude Architectures".
> 
> 2. remove the "arm64" architecture.
> 
> 3. build it again.
> 
> 
> 
> :-)
> 
> 
> 
> 

You are a life saver! Thank you so much :)
